---
harrow:

  http:
    user_hmac_secret: "{{ vault.http.user_hmac_secret }}"

  filesystem:
    op_log_dir: /var/lib/harrow/op-logs
    git_tmp_dir: /var/tmp/harrow/git-tmp

  email:
    sending_domain: 'example.com'

  services:
    notify_on_failure: false

  victorops:
    enabled: "{{ vault.victorops.enabled }}"
    api_id: "{{ vault.victorops.api_id }}"
    api_key: "{{ vault.victorops.api_key }}"

  aws:
    access_key_id:
    secret_access_key:

  intercom:
    enabled: false
    app_id:
    api_key:

  watchdog:
    enabled: false

  braintree:
    enabled: false
    environment: 'sandbox'
    merchant_id: ''
    public_key: ''
    private_key: ''

  limits_store:
    cache_path: /tmp

  github:
    oauth:
      import_repository:
        enabled: true
      authentication:
        enabled: true
      app_id: e283dc31b791c3cdb282
      app_secret: a7d1857c76c11b5330d62859a117e7261e9d50f9
      redirect_uri_pattern: 'https://www.${domain}/#/a/github/callback/%s'

  features:
    trial_period:
      enabled: false
    limits:
      enabled: true
    guest_account:
      enabled: true
    public_projects:
      enabled: true

  rabbitmq:
    virtual_hosts:
      - environment: development
        name: "{{ shared.rabbitmq.development.name }}"
        host: "127.0.0.1"
        port: 5672
        username: "{{ shared.rabbitmq.development.username }}"
        password: "{{ vault.rabbitmq.development.password }}"
      - environment: production
        name: "{{ shared.rabbitmq.production.name }}"
        host: "127.0.0.1"
        port: 5672
        username: "{{ shared.rabbitmq.production.username }}"
        password: "{{ vault.rabbitmq.production.password }}"
      - environment: test
        name: "harrow_test"
        host: "127.0.0.1"
        port: 5672
        username: "test"
        password: "test"

  postgresql:
    databases:
      - environment: test
        name: harrow_test
        password: test
        port: 5432
        sslmode: 'disable'
        host: '/var/run/postgresql/'
        username: test
      - environment: development
        name: "{{ shared.postgresql.development.name }}"
        username: "{{ shared.postgresql.development.username }}"
        password: "{{ vault.postgresql.development.password }}"
        port: 5432
        host: '/var/run/postgresql/'
        sslmode: 'disable'
      - environment: production
        name: "{{ shared.postgresql.production.name }}"
        username: "{{ shared.postgresql.production.username }}"
        password: "{{ vault.postgresql.production.password }}"
        port: 5432
        host: 127.0.0.1
        sslmode: 'disable'

  environment: production

  operator:
    ssh_key: "{{ vault.operator_ssh_key }}"
    filename: /etc/harrow/operator_ssh_key
